export const GET_ORDERS = 'GET_ORDERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const DELETE_ORDERS = 'DELETE_ORDERS';
export const SET_UPDATING_ORDER = 'SET_UPDATING_ORDER';
export const REMOVE_UPDATING_ORDER = 'REMOVE_UPDATING_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const SET_ORDERS_ID_TO_SELECTED = 'SET_ORDERS_ID_TO_SELECTED';

export const SET_TABLE_LOADING = 'SET_TABLE_LOADING';

export const ORDER_ERROR = 'ORDER_ERROR';
