export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_REQUEST';

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';

export const DELETE_ORDER_REQUEST = 'GET_ORDERS_REQUEST';
export const DELETE_ORDER_SUCCESS = 'GET_ORDERS_REQUEST';

export const ORDER_ERROR = 'ORDER_ERROR';
