export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const DELETE_ORDER_SUCCESS = 'GET_ORDERS_SUCCESS';

export const SET_TABLE_LOADING = 'SET_TABLE_LOADING';

export const ORDER_ERROR = 'ORDER_ERROR';
